# -*- coding: utf-8 -*-
"""SOAP Note Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17sZkqcYHZw8YEoPof8XKucDRzD-Yx1DC
"""

!pip install -q transformers accelerate sentencepiece spacy torch
!python -m spacy download en_core_web_sm

# - Imports -
import re
import json
import torch
import spacy
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    pipeline
)

# - NLP -
nlp = spacy.load("en_core_web_sm")


# - MedAlpaca (clinical generation) -
tokenizer = AutoTokenizer.from_pretrained(
    "medalpaca/medalpaca-7b",
    use_fast=False
)

model = AutoModelForCausalLM.from_pretrained(
    "medalpaca/medalpaca-7b",
    device_map="auto",
    torch_dtype=torch.float16
)

def generate_structured_soap(conversation_text):

    # - Clean transcript -
    text = re.sub(r"\*{1,3}|>+|\[.*?\]", "", conversation_text)
    text = re.sub(r"(Doctor:|Physician:|Patient:)", "", text, flags=re.I)
    text = re.sub(r"\b(Mr|Ms|Mrs)\.?\s+\w+", "the patient", text)
    text = re.sub(r"\s+", " ", text).strip()

    # - Route sentences -
    sections = {k: [] for k in ["Subjective", "Objective", "Assessment", "Plan"]}

    for sent in nlp(text).sents:
        s = sent.text.strip()
        l = s.lower()

        if len(s) < 10:
            continue

        if any(w in l for w in ["pain", "ache", "discomfort", "felt", "hit", "accident", "experience"]):
            sections["Subjective"].append(s)

        elif any(w in l for w in ["exam", "range", "movement", "tender", "normal", "signs"]):
            sections["Objective"].append(s)

        elif any(w in l for w in ["diagnosis", "diagnosed", "whiplash", "strain"]):
            sections["Assessment"].append(s)

        elif any(w in l for w in ["physio", "medication", "painkiller", "follow", "return", "recover"]):
            sections["Plan"].append(s)

    subj = " ".join(sections["Subjective"])
    obj = " ".join(sections["Objective"])
    assess = " ".join(sections["Assessment"])
    plan = " ".join(sections["Plan"])

    # - MedAlpaca helper -
    def extract(prompt, text, max_tokens=120):
        if not text.strip():
            return ""

        full_prompt = f"""Clinical transcript:
{text}

Task: {prompt}

Answer:"""

        inputs = tokenizer(full_prompt, return_tensors="pt").to(model.device)
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=0.3,
            do_sample=False
        )
        decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
        return decoded.split("Answer:")[-1].strip()

    # -  extraction -
    chief = extract(
        "Extract the patient's main presenting symptom as a brief clinical phrase.",
        subj,
        30
    )

    hpi = extract(
        "Summarize the history of present illness focusing on onset, progression, and current status.",
        subj,
        150
    )

    exam = extract(
        "Summarize physical examination findings only.",
        obj,
        120
    )

    observations = extract(
        "Summarize observable clinical condition and general appearance.",
        obj,
        80
    )

    diagnosis = (
        "Whiplash injury with neck and back strain"
        if "whiplash" in assess.lower()
        else extract(
            "Extract the clinical diagnosis.",
            assess,
            60
        )
    )

    severity = extract(
        "Assess overall severity and clinical course (e.g., mild, moderate, improving).",
        subj + " " + assess,
        40
    )

    treatment = extract(
        "Summarize treatments and management steps taken.",
        plan,
        120
    )

    follow_up = extract(
        "Extract follow-up instructions or recommendations.",
        plan,
        60
    )

    # - Final SOAP -
    return {
        "Subjective": {
            "Chief_Complaint": chief,
            "History_of_Present_Illness": hpi
        },
        "Objective": {
            "Physical_Exam": exam,
            "Observations": observations
        },
        "Assessment": {
            "Diagnosis": diagnosis,
            "Severity": severity
        },
        "Plan": {
            "Treatment": treatment,
            "Follow_Up": follow_up
        }
    }


    return soap

conversation_text =  """
> **Physician:** *Good morning, Ms. Jones. How are you feeling today?*
>
>
> **Patient:** *Good morning, doctor. I’m doing better, but I still have some discomfort now and then.*
>
> **Physician:** *I understand you were in a car accident last September. Can you walk me through what happened?*
>
> **Patient:** *Yes, it was on September 1st, around 12:30 in the afternoon. I was driving from Cheadle Hulme to Manchester when I had to stop in traffic. Out of nowhere, another car hit me from behind, which pushed my car into the one in front.*
>
> **Physician:** *That sounds like a strong impact. Were you wearing your seatbelt?*
>
> **Patient:** *Yes, I always do.*
>
> **Physician:** *What did you feel immediately after the accident?*
>
> **Patient:** *At first, I was just shocked. But then I realized I had hit my head on the steering wheel, and I could feel pain in my neck and back almost right away.*
>
> **Physician:** *Did you seek medical attention at that time?*
>
> **Patient:** *Yes, I went to Moss Bank Accident and Emergency. They checked me over and said it was a whiplash injury, but they didn’t do any X-rays. They just gave me some advice and sent me home.*
>
> **Physician:** *How did things progress after that?*
>
> **Patient:** *The first four weeks were rough. My neck and back pain were really bad—I had trouble sleeping and had to take painkillers regularly. It started improving after that, but I had to go through ten sessions of physiotherapy to help with the stiffness and discomfort.*
>
> **Physician:** *That makes sense. Are you still experiencing pain now?*
>
> **Patient:** *It’s not constant, but I do get occasional backaches. It’s nothing like before, though.*
>
> **Physician:** *That’s good to hear. Have you noticed any other effects, like anxiety while driving or difficulty concentrating?*
>
> **Patient:** *No, nothing like that. I don’t feel nervous driving, and I haven’t had any emotional issues from the accident.*
>
> **Physician:** *And how has this impacted your daily life? Work, hobbies, anything like that?*
>
> **Patient:** *I had to take a week off work, but after that, I was back to my usual routine. It hasn’t really stopped me from doing anything.*
>
> **Physician:** *That’s encouraging. Let’s go ahead and do a physical examination to check your mobility and any lingering pain.*
>
> [**Physical Examination Conducted**]
>
> **Physician:** *Everything looks good. Your neck and back have a full range of movement, and there’s no tenderness or signs of lasting damage. Your muscles and spine seem to be in good condition.*
>
> **Patient:** *That’s a relief!*
>
> **Physician:** *Yes, your recovery so far has been quite positive. Given your progress, I’d expect you to make a full recovery within six months of the accident. There are no signs of long-term damage or degeneration.*
>
> **Patient:** *That’s great to hear. So, I don’t need to worry about this affecting me in the future?*
>
> **Physician:** *That’s right. I don’t foresee any long-term impact on your work or daily life. If anything changes or you experience worsening symptoms, you can always come back for a follow-up. But at this point, you’re on track for a full recovery.*
>
> **Patient:** *Thank you, doctor. I appreciate it.*
>
> **Physician:** *You’re very welcome, Ms. Jones. Take care, and don’t hesitate to reach out if you need anything.*
>
"""

soap_output = generate_structured_soap(conversation_text)

# - Output -
print(json.dumps(soap_output, indent=2))

# -Save to JSON -
with open("soap_note_output.json", "w") as f:
    json.dump(soap_output, f, indent=2)

print("\nSOAP note saved to soap_note_output.json")